version: '3'
services:
  redis:
    image: redis:latest

  mongo:
    image: mongo:latest
    ports: 
      - "27017:27017"

  web:
    volumes:
      - .:/agario
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    command: npm start
    ports:
      - "8080:8080"
