module.exports = {
    KEY_ESC: 27,
    KEY_ENTER: 13,
    KEY_SPLIT: 32,
    KEY_LEFT: 37,
    KEY_UP: 38,
    KEY_RIGHT: 39,
    KEY_DOWN: 40,
    KEY_LEFT1: 65,
    KEY_RIGHT1: 68,
    KEY_UP1: 87,
    KEY_DOWN1: 83,
    gameStart: true,
    disconnect: false,
    borderDraw: false,
    spin: -Math.PI,
    enemySpin: -Math.PI,
    mobile: false,
    foodSides: 10,
    virusSides: 20,
    lineColor: '#000',
    xoffset: -0,
    yoffset: -0,
    gameWidth: 0,
    gameHeight: 0,
    scrWidth: window.innerWidth,
    scrHeight: window.innerHeight,
    backgroundColor: '#ffd6c0',
    disconnect : false
};
